version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=replace-me
      - OTX_API_KEY=replace-me
      - SHODAN_API_KEY=replace-me
      - CENSYS_UID=replace-me
      - CENSYS_SECRET=replace-me
      - VT_API_KEY=replace-me

  frontend:
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://backend:8000/api/v1
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
